---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.0
  - name: centos-6.6

suites:
  - name: default
    driver_config:
      network:
        - [ "forwarded_port", { guest: 80, host: 8080 } ]
    run_list:
      - recipe[idp-installer-jenkins::default]
    excludes:
      - centos-6.6
  - name: slave
    run_list:
      - recipe[idp-installer-jenkins::slave]
